eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRlOGIxZjY3Zjg2MDhmZWJiMjczMjkiLCJpYXQiOjE2NDkzMTQ1OTF9.VJeuIb_6IZ1mcpite4CA08QYfI3v4y7vFtiedGTYAgI
###

POST http://localhost:3000/signup
content-type: application/json

{
  "email":"test@test.com",
  "password":"mypassword"
}
###

GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRlOGIxZjY3Zjg2MDhmZWJiMjczMjkiLCJpYXQiOjE2NDkzMTQ1OTF9.VJeuIb_6IZ1mcpite4CA08QYfI3v4y7vFtiedGTYAgI

###

POST http://localhost:3000/signin
content-type: application/json

{
  "email":"test@test.com",
  "password":"mypassword"
}
###

GET http://localhost:3000/tracks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRlOGIxZjY3Zjg2MDhmZWJiMjczMjkiLCJpYXQiOjE2NDkzMTQ1OTF9.VJeuIb_6IZ1mcpite4CA08QYfI3v4y7vFtiedGTYAgI